- hosts: all
  gather_facts: true

  roles:
  - { role: install-proxy, tags: ["install-proxy"] }
  - { role: configure-proxys, tags: ["configure-proxys"] }
  - { role: install-agent, tags: ["install-agent"] }