- name: Install zabbix-agent
  apt:
    name: zabbix-agent

#- name: Reiniciando o proxy
#  service:
#    name: zabbix-proxy
#    state: restarted

- name: Verificando o status do agent
  service:
    name: zabbix-agent
    state: started
  register: service

- debug:
    msg: ">> {{ service.status.Names  }} : {{ service.status.ActiveState }} : {{ service.status.SubState }}"
...
