- name: Parando os serviços zabbix-proxy stage e prod
  systemd:
    state: stopped
    name: zabbix-proxy-{{  item  }}
  loop:
    - "{{  env.prod.type  }}"
    - "{{  env.stage.type  }}"

- name: Removendo diretorios para zabbix stage e prod
  file:
    path: "{{  item  }}"
    state: absent
  loop:
    - "{{  env.prod.socketdir  }}"
    - "{{  env.stage.socketdir  }}"

- name: Removendo arquivos de serviço para zabbix-proxy stage e prod
  file:
    path: /lib/systemd/system/zabbix-proxy-{{  item.type  }}.service
    state: absent
  loop:
    - "{{  env.prod  }}"
    - "{{  env.stage  }}"

- name: Removendo arquivos de conf para zabbix-proxy stage e prod
  file:
    path: /etc/zabbix/zabbix_proxy_{{  item.type  }}.conf
    state: absent
  loop:
    - "{{  env.prod  }}"
    - "{{  env.stage  }}"

- name: Executando systemd reload
  systemd:
    daemon_reload: yes

- name: Removendo zabbix-proxy-sqlite3 e release
  apt:
    name: 
      - zabbix-proxy-sqlite3
      - zabbix-release
    state: absent
    purge: yes
